In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

import polars as pl

from config import (
    RAW_DATA_DIR,
    SAML_D_DATASET_HANDLE,
    SAML_D_FILE_NAME
)

from src.data.acquisition import KaggleDatasetDownloader
from src.data.loader import SAMLDDataLoader
from src.data.validation import SAMLDDataValidator

In [2]:
### data acquisition
# create a downloader instance
downloader = KaggleDatasetDownloader(
    dataset_handle = SAML_D_DATASET_HANDLE,
    file_name = SAML_D_FILE_NAME,
    destination_dir = RAW_DATA_DIR
)

# download the raw SAML-D dataset
raw_data_path = downloader.download(
    force = False
)

raw_data_path

Downloading to /Users/gorkemy/Desktop/Projects/Graph-based Financial Crime/data/raw/SAML-D.csv...

100%|██████████| 193M/193M [00:13<00:00, 14.6MB/s]

Extracting zip of SAML-D.csv...

PosixPath('/Users/gorkemy/Desktop/Projects/Graph-based Financial Crime/data/raw/SAML-D.csv')

In [3]:
### data inspection
# create a loader instance
loader = SAMLDDataLoader(
    raw_data_path = raw_data_path
)

# create lazy query plan
raw_lazy_frame = loader.scan_raw()

# display LazyFrame schema
display(raw_lazy_frame.collect_schema())

# load a LazyFrame sample
raw_sample = loader.load_raw_sample(
    n_rows = 10_000
)

# inspect first 10 rows
display(raw_sample.head(10))

# inspecting the primary label
display(
    raw_sample
    .group_by('Is_laundering')
    .len()
)

Schema([('Time', String),
        ('Date', String),
        ('Sender_account', String),
        ('Receiver_account', String),
        ('Amount', Float64),
        ('Payment_currency', String),
        ('Received_currency', String),
        ('Sender_bank_location', String),
        ('Receiver_bank_location', String),
        ('Payment_type', String),
        ('Is_laundering', Int8),
        ('Laundering_type', String)])

shape: (10, 12)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Time     ┆ Date      ┆ Sender_ac ┆ Receiver_ ┆ … ┆ Receiver_ ┆ Payment_t ┆ Is_launde ┆ Launderin │
│ ---      ┆ ---       ┆ count     ┆ account   ┆   ┆ bank_loca ┆ ype       ┆ ring      ┆ g_type    │
│ str      ┆ str       ┆ ---       ┆ ---       ┆   ┆ tion      ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ i8        ┆ str       │
│          ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10:35:19 ┆ 2022-10-0 ┆ 872473195 ┆ 276935542 ┆ … ┆ UK        ┆ Cash      ┆ 0         ┆ Normal_Ca │
│          ┆ 7         ┆ 5         ┆ 6         ┆   ┆           ┆ Deposit   ┆           ┆ sh_Deposi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ts        │
│ 10:35:20 ┆ 2022-10-0 ┆ 149198906 ┆ 840125533 ┆ … ┆ UAE       ┆ Cross-bor ┆ 0         ┆ Normal_Fa │
│          ┆ 7         ┆ 4         ┆ 5         ┆   ┆           ┆ der       ┆           ┆ n_Out     │
│ 10:35:20 ┆ 2022-10-0 ┆ 287305149 ┆ 440476700 ┆ … ┆ UK        ┆ Cheque    ┆ 0         ┆ Normal_Sm │
│          ┆ 7         ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆ all_Fan_O │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ut        │
│ 10:35:21 ┆ 2022-10-0 ┆ 537665243 ┆ 960042022 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Fa │
│          ┆ 7         ┆ 7         ┆ 0         ┆   ┆           ┆           ┆           ┆ n_In      │
│ 10:35:21 ┆ 2022-10-0 ┆ 961418617 ┆ 380333697 ┆ … ┆ UK        ┆ Cash      ┆ 0         ┆ Normal_Ca │
│          ┆ 7         ┆ 8         ┆ 2         ┆   ┆           ┆ Deposit   ┆           ┆ sh_Deposi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ts        │
│ 10:35:21 ┆ 2022-10-0 ┆ 897455926 ┆ 314354751 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Gr │
│          ┆ 7         ┆ 8         ┆ 1         ┆   ┆           ┆           ┆           ┆ oup       │
│ 10:35:23 ┆ 2022-10-0 ┆ 980191499 ┆ 857763595 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Sm │
│          ┆ 7         ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆ all_Fan_O │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ut        │
│ 10:35:23 ┆ 2022-10-0 ┆ 805779330 ┆ 935089621 ┆ … ┆ UK        ┆ Credit    ┆ 0         ┆ Normal_Sm │
│          ┆ 7         ┆ 8         ┆ 3         ┆   ┆           ┆ card      ┆           ┆ all_Fan_O │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ut        │
│ 10:35:26 ┆ 2022-10-0 ┆ 611665726 ┆ 656192169 ┆ … ┆ UK        ┆ Cheque    ┆ 0         ┆ Normal_Fa │
│          ┆ 7         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆ n_Out     │
│ 10:35:29 ┆ 2022-10-0 ┆ 742145175 ┆ 275570907 ┆ … ┆ UK        ┆ Credit    ┆ 0         ┆ Normal_Fa │
│          ┆ 7         ┆ 2         ┆ 1         ┆   ┆           ┆ card      ┆           ┆ n_Out     │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (2, 2)
┌───────────────┬──────┐
│ Is_laundering ┆ len  │
│ ---           ┆ ---  │
│ i8            ┆ u32  │
╞═══════════════╪══════╡
│ 0             ┆ 9987 │
│ 1             ┆ 13   │
└───────────────┴──────┘

In [4]:
### data validation
# raw data content validation
raw_content_summary = SAMLDDataValidator.validate_content(
    lazy_frame = raw_lazy_frame
)

raw_content_summary_frame = pl.DataFrame(
    [raw_content_summary]
)

with pl.Config(
    tbl_rows=-1
):
    display(
    raw_content_summary_frame
    .transpose(
        include_header = True,
        header_name = 'metric',
        column_names = ['value']
    )
)

shape: (23, 2)
┌─────────────────────────────────┬─────────┐
│ metric                          ┆ value   │
│ ---                             ┆ ---     │
│ str                             ┆ i64     │
╞═════════════════════════════════╪═════════╡
│ row_count                       ┆ 9504852 │
│ time_null_count                 ┆ 0       │
│ date_null_count                 ┆ 0       │
│ sender_account_null_count       ┆ 0       │
│ receiver_account_null_count     ┆ 0       │
│ amount_null_count               ┆ 0       │
│ payment_currency_null_count     ┆ 0       │
│ received_currency_null_count    ┆ 0       │
│ sender_bank_location_null_coun… ┆ 0       │
│ receiver_bank_location_null_co… ┆ 0       │
│ payment_type_null_count         ┆ 0       │
│ is_laundering_null_count        ┆ 0       │
│ laundering_type_null_count      ┆ 0       │
│ empty_sender_account_count      ┆ 0       │
│ empty_receiver_account_count    ┆ 0       │
│ nan_amount_count                ┆ 0       │
│ infinite_amount_count           ┆ 0       │
│ non_positive_amount_count       ┆ 0       │
│ invalid_label_count             ┆ 0       │
│ normal_transaction_count        ┆ 9494979 │
│ laundering_transaction_count    ┆ 9873    │
│ unparseable_timestamp_count     ┆ 0       │
│ self_transfer_count             ┆ 0       │
└─────────────────────────────────┴─────────┘