In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

import numpy as np
import polars as pl

from src.data.loader import SAMLDDataLoader

from src.analysis.transaction_eda import SAMLDTransactionEDA

In [2]:
### load standardized transactions
# create loader instance
loader = SAMLDDataLoader()

# lazily scan transactions from interim Parquet dataset
transactions = loader.scan_interim()

# create transaction EDA instance
transaction_eda = SAMLDTransactionEDA(
    transactions = transactions
)

In [3]:
### dataset and target overview
# dataset overview
transaction_overview = transaction_eda.get_transaction_overview()

# target overview
label_distribution = transaction_eda.get_label_distribution()

display(transaction_overview)
display(label_distribution)

shape: (1, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ transacti ┆ unique_tr ┆ unique_se ┆ unique_re ┆ … ┆ launderin ┆ minimum_t ┆ maximum_t ┆ launderi │
│ on_count  ┆ ansaction ┆ nder_acco ┆ ceiver_ac ┆   ┆ g_transac ┆ imestamp  ┆ imestamp  ┆ ng_rate  │
│ ---       ┆ _id_count ┆ unt       ┆ count     ┆   ┆ tion_coun ┆ ---       ┆ ---       ┆ ---      │
│ u64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ t         ┆ datetime[ ┆ datetime[ ┆ f64      │
│           ┆ u64       ┆ u64       ┆ u64       ┆   ┆ ---       ┆ μs]       ┆ μs]       ┆          │
│           ┆           ┆           ┆           ┆   ┆ u64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 9504852   ┆ 9504852   ┆ 292715    ┆ 652266    ┆ … ┆ 9873      ┆ 2022-10-0 ┆ 2023-08-2 ┆ 0.001039 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 3         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 10:35:19  ┆ 10:57:12  ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (2, 4)
┌───────────────┬────────────┬───────────────────┬───────────────────┐
│ is_laundering ┆ label      ┆ transaction_count ┆ transaction_share │
│ ---           ┆ ---        ┆ ---               ┆ ---               │
│ i8            ┆ str        ┆ u64               ┆ f64               │
╞═══════════════╪════════════╪═══════════════════╪═══════════════════╡
│ 0             ┆ normal     ┆ 9494979           ┆ 0.998961          │
│ 1             ┆ laundering ┆ 9873              ┆ 0.001039          │
└───────────────┴────────────┴───────────────────┴───────────────────┘

In [4]:
### daily transaction activity
# daily activity
daily_activity = transaction_eda.get_daily_activity()

display(daily_activity)

shape: (321, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ transaction_da ┆ transaction_co ┆ laundering_tra ┆ active_sender ┆ active_receiv ┆ laundering_ra │
│ te             ┆ unt            ┆ nsaction_count ┆ _count        ┆ er_account    ┆ te            │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ date           ┆ u64            ┆ u64            ┆ u64           ┆ u64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2022-10-07     ┆ 20892          ┆ 27             ┆ 9110          ┆ 11111         ┆ 0.001292      │
│ 2022-10-08     ┆ 29023          ┆ 29             ┆ 10072         ┆ 13863         ┆ 0.000999      │
│ 2022-10-09     ┆ 28880          ┆ 32             ┆ 10300         ┆ 13570         ┆ 0.001108      │
│ 2022-10-10     ┆ 27345          ┆ 32             ┆ 11123         ┆ 14632         ┆ 0.00117       │
│ 2022-10-11     ┆ 28704          ┆ 30             ┆ 11248         ┆ 14782         ┆ 0.001045      │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 2023-08-19     ┆ 28206          ┆ 29             ┆ 10947         ┆ 14565         ┆ 0.001028      │
│ 2023-08-20     ┆ 30745          ┆ 36             ┆ 11012         ┆ 14764         ┆ 0.001171      │
│ 2023-08-21     ┆ 29094          ┆ 48             ┆ 12009         ┆ 15526         ┆ 0.00165       │
│ 2023-08-22     ┆ 28443          ┆ 39             ┆ 11894         ┆ 15127         ┆ 0.001371      │
│ 2023-08-23     ┆ 8400           ┆ 7              ┆ 4504          ┆ 4887          ┆ 0.000833      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [5]:
### categorical summaries
# payment type categorical summary
payment_type_summary = transaction_eda.get_categorical_summary(
    column_name = 'payment_type'
)

# payment currency categorical summary
payment_currency_summary = transaction_eda.get_categorical_summary(
    column_name = 'payment_currency'
)

# received currency categorical summary
received_currency_summary = transaction_eda.get_categorical_summary(
    column_name = 'received_currency'
)

# sender bank location categorical summary
sender_location_summary = transaction_eda.get_categorical_summary(
    column_name = 'sender_bank_location'
)

# receiver bank location categorical summary
receiver_location_summary = transaction_eda.get_categorical_summary(
    column_name = 'receiver_bank_location'
)

with pl.Config(tbl_rows = -1):
    display(payment_type_summary)
    display(payment_currency_summary)
    display(received_currency_summary)
    display(sender_location_summary)
    display(receiver_location_summary)

shape: (7, 5)
┌─────────────────┬───────────────────┬──────────────────────┬───────────────────┬─────────────────┐
│ payment_type    ┆ transaction_count ┆ laundering_transacti ┆ transaction_share ┆ laundering_rate │
│ ---             ┆ ---               ┆ on_count             ┆ ---               ┆ ---             │
│ str             ┆ u64               ┆ ---                  ┆ f64               ┆ f64             │
│                 ┆                   ┆ u64                  ┆                   ┆                 │
╞═════════════════╪═══════════════════╪══════════════════════╪═══════════════════╪═════════════════╡
│ Credit card     ┆ 2012909           ┆ 1136                 ┆ 0.211777          ┆ 0.000564        │
│ Debit card      ┆ 2012103           ┆ 1124                 ┆ 0.211692          ┆ 0.000559        │
│ Cheque          ┆ 2011419           ┆ 1087                 ┆ 0.21162           ┆ 0.00054         │
│ ACH             ┆ 2008807           ┆ 1159                 ┆ 0.211345          ┆ 0.000577        │
│ Cross-border    ┆ 933931            ┆ 2628                 ┆ 0.098258          ┆ 0.002814        │
│ Cash Withdrawal ┆ 300477            ┆ 1334                 ┆ 0.031613          ┆ 0.00444         │
│ Cash Deposit    ┆ 225206            ┆ 1405                 ┆ 0.023694          ┆ 0.006239        │
└─────────────────┴───────────────────┴──────────────────────┴───────────────────┴─────────────────┘

shape: (13, 5)
┌──────────────────┬───────────────────┬─────────────────────┬───────────────────┬─────────────────┐
│ payment_currency ┆ transaction_count ┆ laundering_transact ┆ transaction_share ┆ laundering_rate │
│ ---              ┆ ---               ┆ ion_count           ┆ ---               ┆ ---             │
│ str              ┆ u64               ┆ ---                 ┆ f64               ┆ f64             │
│                  ┆                   ┆ u64                 ┆                   ┆                 │
╞══════════════════╪═══════════════════╪═════════════════════╪═══════════════════╪═════════════════╡
│ UK pounds        ┆ 9099293           ┆ 8830                ┆ 0.957331          ┆ 0.00097         │
│ Euro             ┆ 117164            ┆ 260                 ┆ 0.012327          ┆ 0.002219        │
│ Turkish lira     ┆ 27996             ┆ 73                  ┆ 0.002945          ┆ 0.002608        │
│ Swiss franc      ┆ 27492             ┆ 82                  ┆ 0.002892          ┆ 0.002983        │
│ Dirham           ┆ 27263             ┆ 89                  ┆ 0.002868          ┆ 0.003264        │
│ Pakistani rupee  ┆ 27196             ┆ 62                  ┆ 0.002861          ┆ 0.00228         │
│ Naira            ┆ 27143             ┆ 62                  ┆ 0.002856          ┆ 0.002284        │
│ US dollar        ┆ 26061             ┆ 60                  ┆ 0.002742          ┆ 0.002302        │
│ Yen              ┆ 25562             ┆ 65                  ┆ 0.002689          ┆ 0.002543        │
│ Moroccan dirham  ┆ 25395             ┆ 90                  ┆ 0.002672          ┆ 0.003544        │
│ Mexican Peso     ┆ 24852             ┆ 68                  ┆ 0.002615          ┆ 0.002736        │
│ Albanian lek     ┆ 24778             ┆ 64                  ┆ 0.002607          ┆ 0.002583        │
│ Indian rupee     ┆ 24657             ┆ 68                  ┆ 0.002594          ┆ 0.002758        │
└──────────────────┴───────────────────┴─────────────────────┴───────────────────┴─────────────────┘

shape: (13, 5)
┌───────────────────┬───────────────────┬────────────────────┬───────────────────┬─────────────────┐
│ received_currency ┆ transaction_count ┆ laundering_transac ┆ transaction_share ┆ laundering_rate │
│ ---               ┆ ---               ┆ tion_count         ┆ ---               ┆ ---             │
│ str               ┆ u64               ┆ ---                ┆ f64               ┆ f64             │
│                   ┆                   ┆ u64                ┆                   ┆                 │
╞═══════════════════╪═══════════════════╪════════════════════╪═══════════════════╪═════════════════╡
│ UK pounds         ┆ 8783655           ┆ 6919               ┆ 0.924123          ┆ 0.000788        │
│ Euro              ┆ 231911            ┆ 716                ┆ 0.024399          ┆ 0.003087        │
│ Pakistani rupee   ┆ 45993             ┆ 204                ┆ 0.004839          ┆ 0.004435        │
│ Yen               ┆ 45814             ┆ 118                ┆ 0.00482           ┆ 0.002576        │
│ Moroccan dirham   ┆ 45748             ┆ 285                ┆ 0.004813          ┆ 0.00623         │
│ Albanian lek      ┆ 45736             ┆ 262                ┆ 0.004812          ┆ 0.005729        │
│ Mexican Peso      ┆ 45255             ┆ 235                ┆ 0.004761          ┆ 0.005193        │
│ Naira             ┆ 45046             ┆ 288                ┆ 0.004739          ┆ 0.006393        │
│ Indian rupee      ┆ 43757             ┆ 172                ┆ 0.004604          ┆ 0.003931        │
│ US dollar         ┆ 43664             ┆ 118                ┆ 0.004594          ┆ 0.002702        │
│ Swiss franc       ┆ 42931             ┆ 113                ┆ 0.004517          ┆ 0.002632        │
│ Dirham            ┆ 42797             ┆ 225                ┆ 0.004503          ┆ 0.005257        │
│ Turkish lira      ┆ 42545             ┆ 218                ┆ 0.004476          ┆ 0.005124        │
└───────────────────┴───────────────────┴────────────────────┴───────────────────┴─────────────────┘

shape: (18, 5)
┌────────────────────┬───────────────────┬───────────────────┬───────────────────┬─────────────────┐
│ sender_bank_locati ┆ transaction_count ┆ laundering_transa ┆ transaction_share ┆ laundering_rate │
│ on                 ┆ ---               ┆ ction_count       ┆ ---               ┆ ---             │
│ ---                ┆ u64               ┆ ---               ┆ f64               ┆ f64             │
│ str                ┆                   ┆ u64               ┆                   ┆                 │
╞════════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪═════════════════╡
│ UK                 ┆ 9183088           ┆ 9253              ┆ 0.966147          ┆ 0.001008        │
│ Turkey             ┆ 20902             ┆ 27                ┆ 0.002199          ┆ 0.001292        │
│ Switzerland        ┆ 20503             ┆ 41                ┆ 0.002157          ┆ 0.002           │
│ Pakistan           ┆ 20346             ┆ 25                ┆ 0.002141          ┆ 0.001229        │
│ UAE                ┆ 20081             ┆ 34                ┆ 0.002113          ┆ 0.001693        │
│ Nigeria            ┆ 20027             ┆ 25                ┆ 0.002107          ┆ 0.001248        │
│ Spain              ┆ 19391             ┆ 27                ┆ 0.00204           ┆ 0.001392        │
│ Germany            ┆ 19259             ┆ 43                ┆ 0.002026          ┆ 0.002233        │
│ USA                ┆ 19027             ┆ 36                ┆ 0.002002          ┆ 0.001892        │
│ Italy              ┆ 18895             ┆ 45                ┆ 0.001988          ┆ 0.002382        │
│ France             ┆ 18702             ┆ 31                ┆ 0.001968          ┆ 0.001658        │
│ Japan              ┆ 18468             ┆ 38                ┆ 0.001943          ┆ 0.002058        │
│ Morocco            ┆ 18437             ┆ 55                ┆ 0.00194           ┆ 0.002983        │
│ Austria            ┆ 18050             ┆ 38                ┆ 0.001899          ┆ 0.002105        │
│ Mexico             ┆ 17662             ┆ 44                ┆ 0.001858          ┆ 0.002491        │
│ Albania            ┆ 17648             ┆ 28                ┆ 0.001857          ┆ 0.001587        │
│ India              ┆ 17596             ┆ 42                ┆ 0.001851          ┆ 0.002387        │
│ Netherlands        ┆ 16770             ┆ 41                ┆ 0.001764          ┆ 0.002445        │
└────────────────────┴───────────────────┴───────────────────┴───────────────────┴─────────────────┘

shape: (18, 5)
┌────────────────────┬───────────────────┬───────────────────┬───────────────────┬─────────────────┐
│ receiver_bank_loca ┆ transaction_count ┆ laundering_transa ┆ transaction_share ┆ laundering_rate │
│ tion               ┆ ---               ┆ ction_count       ┆ ---               ┆ ---             │
│ ---                ┆ u64               ┆ ---               ┆ f64               ┆ f64             │
│ str                ┆                   ┆ u64               ┆                   ┆                 │
╞════════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪═════════════════╡
│ UK                 ┆ 8864634           ┆ 7308              ┆ 0.932643          ┆ 0.000824        │
│ Pakistan           ┆ 38980             ┆ 169               ┆ 0.004101          ┆ 0.004336        │
│ Austria            ┆ 38844             ┆ 154               ┆ 0.004087          ┆ 0.003965        │
│ Albania            ┆ 38783             ┆ 235               ┆ 0.00408           ┆ 0.006059        │
│ Japan              ┆ 38729             ┆ 83                ┆ 0.004075          ┆ 0.002143        │
│ Morocco            ┆ 38704             ┆ 253               ┆ 0.004072          ┆ 0.006537        │
│ Germany            ┆ 38540             ┆ 102               ┆ 0.004055          ┆ 0.002647        │
│ France             ┆ 38512             ┆ 82                ┆ 0.004052          ┆ 0.002129        │
│ Mexico             ┆ 38385             ┆ 197               ┆ 0.004038          ┆ 0.005132        │
│ Nigeria            ┆ 38272             ┆ 251               ┆ 0.004027          ┆ 0.006558        │
│ Netherlands        ┆ 37314             ┆ 148               ┆ 0.003926          ┆ 0.003966        │
│ Spain              ┆ 37288             ┆ 87                ┆ 0.003923          ┆ 0.002333        │
│ India              ┆ 36936             ┆ 137               ┆ 0.003886          ┆ 0.003709        │
│ USA                ┆ 36850             ┆ 87                ┆ 0.003877          ┆ 0.002361        │
│ Italy              ┆ 36517             ┆ 131               ┆ 0.003842          ┆ 0.003587        │
│ Switzerland        ┆ 36081             ┆ 77                ┆ 0.003796          ┆ 0.002134        │
│ UAE                ┆ 35897             ┆ 195               ┆ 0.003777          ┆ 0.005432        │
│ Turkey             ┆ 35586             ┆ 177               ┆ 0.003744          ┆ 0.004974        │
└────────────────────┴───────────────────┴───────────────────┴───────────────────┴─────────────────┘

In [6]:
### currency pair & amount summaries
# currency pair summary
currency_pair_summary = transaction_eda.get_currency_pair_summary()

# amount summary
amount_summary = transaction_eda.get_amount_summary()

with pl.Config(tbl_rows = -1):
    display(currency_pair_summary)
    display(amount_summary)

shape: (169, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ payment_curr ┆ received_cu ┆ transaction ┆ laundering_ ┆ same_curren ┆ transaction ┆ laundering_ │
│ ency         ┆ rrency      ┆ _count      ┆ transaction ┆ cy          ┆ _share      ┆ rate        │
│ ---          ┆ ---         ┆ ---         ┆ _count      ┆ ---         ┆ ---         ┆ ---         │
│ str          ┆ str         ┆ u64         ┆ ---         ┆ bool        ┆ f64         ┆ f64         │
│              ┆             ┆             ┆ u64         ┆             ┆             ┆             │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ UK pounds    ┆ UK pounds   ┆ 8414112     ┆ 6171        ┆ true        ┆ 0.885244    ┆ 0.000733    │
│ UK pounds    ┆ Euro        ┆ 220504      ┆ 625         ┆ false       ┆ 0.023199    ┆ 0.002834    │
│ Euro         ┆ UK pounds   ┆ 106608      ┆ 186         ┆ false       ┆ 0.011216    ┆ 0.001745    │
│ UK pounds    ┆ Pakistani   ┆ 43895       ┆ 187         ┆ false       ┆ 0.004618    ┆ 0.00426     │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ UK pounds    ┆ Yen         ┆ 43517       ┆ 101         ┆ false       ┆ 0.004578    ┆ 0.002321    │
│ UK pounds    ┆ Moroccan    ┆ 43461       ┆ 261         ┆ false       ┆ 0.004573    ┆ 0.006005    │
│              ┆ dirham      ┆             ┆             ┆             ┆             ┆             │
│ UK pounds    ┆ Mexican     ┆ 43174       ┆ 220         ┆ false       ┆ 0.004542    ┆ 0.005096    │
│              ┆ Peso        ┆             ┆             ┆             ┆             ┆             │
│ UK pounds    ┆ Albanian    ┆ 43040       ┆ 232         ┆ false       ┆ 0.004528    ┆ 0.00539     │
│              ┆ lek         ┆             ┆             ┆             ┆             ┆             │
│ UK pounds    ┆ Naira       ┆ 42696       ┆ 261         ┆ false       ┆ 0.004492    ┆ 0.006113    │
│ UK pounds    ┆ Indian      ┆ 41719       ┆ 156         ┆ false       ┆ 0.004389    ┆ 0.003739    │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ UK pounds    ┆ US dollar   ┆ 41571       ┆ 100         ┆ false       ┆ 0.004374    ┆ 0.002406    │
│ UK pounds    ┆ Swiss franc ┆ 40581       ┆ 98          ┆ false       ┆ 0.00427     ┆ 0.002415    │
│ UK pounds    ┆ Dirham      ┆ 40581       ┆ 216         ┆ false       ┆ 0.00427     ┆ 0.005323    │
│ UK pounds    ┆ Turkish     ┆ 40442       ┆ 202         ┆ false       ┆ 0.004255    ┆ 0.004995    │
│              ┆ lira        ┆             ┆             ┆             ┆             ┆             │
│ Turkish lira ┆ UK pounds   ┆ 25548       ┆ 58          ┆ false       ┆ 0.002688    ┆ 0.00227     │
│ Swiss franc  ┆ UK pounds   ┆ 25002       ┆ 55          ┆ false       ┆ 0.00263     ┆ 0.0022      │
│ Dirham       ┆ UK pounds   ┆ 24808       ┆ 62          ┆ false       ┆ 0.00261     ┆ 0.002499    │
│ Pakistani    ┆ UK pounds   ┆ 24774       ┆ 40          ┆ false       ┆ 0.002606    ┆ 0.001615    │
│ rupee        ┆             ┆             ┆             ┆             ┆             ┆             │
│ Naira        ┆ UK pounds   ┆ 24729       ┆ 52          ┆ false       ┆ 0.002602    ┆ 0.002103    │
│ US dollar    ┆ UK pounds   ┆ 23618       ┆ 44          ┆ false       ┆ 0.002485    ┆ 0.001863    │
│ Yen          ┆ UK pounds   ┆ 23417       ┆ 50          ┆ false       ┆ 0.002464    ┆ 0.002135    │
│ Moroccan     ┆ UK pounds   ┆ 23204       ┆ 65          ┆ false       ┆ 0.002441    ┆ 0.002801    │
│ dirham       ┆             ┆             ┆             ┆             ┆             ┆             │
│ Mexican Peso ┆ UK pounds   ┆ 22742       ┆ 45          ┆ false       ┆ 0.002393    ┆ 0.001979    │
│ Albanian lek ┆ UK pounds   ┆ 22727       ┆ 47          ┆ false       ┆ 0.002391    ┆ 0.002068    │
│ Indian rupee ┆ UK pounds   ┆ 22366       ┆ 44          ┆ false       ┆ 0.002353    ┆ 0.001967    │
│ Euro         ┆ Euro        ┆ 3392        ┆ 24          ┆ true        ┆ 0.000357    ┆ 0.007075    │
│ Swiss franc  ┆ Euro        ┆ 855         ┆ 8           ┆ false       ┆ 0.00009     ┆ 0.009357    │
│ Dirham       ┆ Euro        ┆ 842         ┆ 8           ┆ false       ┆ 0.000089    ┆ 0.009501    │
│ Euro         ┆ Moroccan    ┆ 813         ┆ 4           ┆ false       ┆ 0.000086    ┆ 0.00492     │
│              ┆ dirham      ┆             ┆             ┆             ┆             ┆             │
│ Turkish lira ┆ Euro        ┆ 810         ┆ 3           ┆ false       ┆ 0.000085    ┆ 0.003704    │
│ Indian rupee ┆ Euro        ┆ 750         ┆ 7           ┆ false       ┆ 0.000079    ┆ 0.009333    │
│ Euro         ┆ Swiss franc ┆ 744         ┆ 3           ┆ false       ┆ 0.000078    ┆ 0.004032    │
│ US dollar    ┆ Euro        ┆ 739         ┆ 4           ┆ false       ┆ 0.000078    ┆ 0.005413    │
│ Euro         ┆ Albanian    ┆ 734         ┆ 13          ┆ false       ┆ 0.000077    ┆ 0.017711    │
│              ┆ lek         ┆             ┆             ┆             ┆             ┆             │
│ Mexican Peso ┆ Euro        ┆ 721         ┆ 9           ┆ false       ┆ 0.000076    ┆ 0.012483    │
│ Euro         ┆ US dollar   ┆ 714         ┆ 6           ┆ false       ┆ 0.000075    ┆ 0.008403    │
│ Moroccan     ┆ Euro        ┆ 702         ┆ 8           ┆ false       ┆ 0.000074    ┆ 0.011396    │
│ dirham       ┆             ┆             ┆             ┆             ┆             ┆             │
│ Euro         ┆ Naira       ┆ 689         ┆ 8           ┆ false       ┆ 0.000072    ┆ 0.011611    │
│ Naira        ┆ Euro        ┆ 675         ┆ 3           ┆ false       ┆ 0.000071    ┆ 0.004444    │
│ Albanian lek ┆ Euro        ┆ 673         ┆ 5           ┆ false       ┆ 0.000071    ┆ 0.007429    │
│ Euro         ┆ Turkish     ┆ 656         ┆ 2           ┆ false       ┆ 0.000069    ┆ 0.003049    │
│              ┆ lira        ┆             ┆             ┆             ┆             ┆             │
│ Pakistani    ┆ Euro        ┆ 631         ┆ 6           ┆ false       ┆ 0.000066    ┆ 0.009509    │
│ rupee        ┆             ┆             ┆             ┆             ┆             ┆             │
│ Euro         ┆ Dirham      ┆ 628         ┆ 2           ┆ false       ┆ 0.000066    ┆ 0.003185    │
│ Euro         ┆ Yen         ┆ 628         ┆ 2           ┆ false       ┆ 0.000066    ┆ 0.003185    │
│ Yen          ┆ Euro        ┆ 617         ┆ 6           ┆ false       ┆ 0.000065    ┆ 0.009724    │
│ Euro         ┆ Indian      ┆ 588         ┆ 4           ┆ false       ┆ 0.000062    ┆ 0.006803    │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ Euro         ┆ Mexican     ┆ 488         ┆ 5           ┆ false       ┆ 0.000051    ┆ 0.010246    │
│              ┆ Peso        ┆             ┆             ┆             ┆             ┆             │
│ Euro         ┆ Pakistani   ┆ 482         ┆ 1           ┆ false       ┆ 0.000051    ┆ 0.002075    │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ Yen          ┆ Albanian    ┆ 261         ┆ 1           ┆ false       ┆ 0.000027    ┆ 0.003831    │
│              ┆ lek         ┆             ┆             ┆             ┆             ┆             │
│ Pakistani    ┆ Naira       ┆ 243         ┆ 1           ┆ false       ┆ 0.000026    ┆ 0.004115    │
│ rupee        ┆             ┆             ┆             ┆             ┆             ┆             │
│ Naira        ┆ Dirham      ┆ 222         ┆ 0           ┆ false       ┆ 0.000023    ┆ 0.0         │
│ US dollar    ┆ Albanian    ┆ 204         ┆ 1           ┆ false       ┆ 0.000021    ┆ 0.004902    │
│              ┆ lek         ┆             ┆             ┆             ┆             ┆             │
│ Swiss franc  ┆ Albanian    ┆ 203         ┆ 0           ┆ false       ┆ 0.000021    ┆ 0.0         │
│              ┆ lek         ┆             ┆             ┆             ┆             ┆             │
│ Turkish lira ┆ Mexican     ┆ 202         ┆ 1           ┆ false       ┆ 0.000021    ┆ 0.00495     │
│              ┆ Peso        ┆             ┆             ┆             ┆             ┆             │
│ Dirham       ┆ Albanian    ┆ 198         ┆ 1           ┆ false       ┆ 0.000021    ┆ 0.005051    │
│              ┆ lek         ┆             ┆             ┆             ┆             ┆             │
│ Naira        ┆ Yen         ┆ 197         ┆ 0           ┆ false       ┆ 0.000021    ┆ 0.0         │
│ Turkish lira ┆ Pakistani   ┆ 197         ┆ 0           ┆ false       ┆ 0.000021    ┆ 0.0         │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ Dirham       ┆ Mexican     ┆ 192         ┆ 2           ┆ false       ┆ 0.00002     ┆ 0.010417    │
│              ┆ Peso        ┆             ┆             ┆             ┆             ┆             │
│ Pakistani    ┆ Yen         ┆ 191         ┆ 1           ┆ false       ┆ 0.00002     ┆ 0.005236    │
│ rupee        ┆             ┆             ┆             ┆             ┆             ┆             │
│ US dollar    ┆ Moroccan    ┆ 190         ┆ 0           ┆ false       ┆ 0.00002     ┆ 0.0         │
│              ┆ dirham      ┆             ┆             ┆             ┆             ┆             │
│ Naira        ┆ Moroccan    ┆ 188         ┆ 1           ┆ false       ┆ 0.00002     ┆ 0.005319    │
│              ┆ dirham      ┆             ┆             ┆             ┆             ┆             │
│ Pakistani    ┆ US dollar   ┆ 187         ┆ 3           ┆ false       ┆ 0.00002     ┆ 0.016043    │
│ rupee        ┆             ┆             ┆             ┆             ┆             ┆             │
│ Pakistani    ┆ Pakistani   ┆ 184         ┆ 4           ┆ true        ┆ 0.000019    ┆ 0.021739    │
│ rupee        ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ Pakistani    ┆ Dirham      ┆ 182         ┆ 0           ┆ false       ┆ 0.000019    ┆ 0.0         │
│ rupee        ┆             ┆             ┆             ┆             ┆             ┆             │
│ US dollar    ┆ Naira       ┆ 181         ┆ 2           ┆ false       ┆ 0.000019    ┆ 0.01105     │
│ Mexican Peso ┆ Albanian    ┆ 179         ┆ 2           ┆ false       ┆ 0.000019    ┆ 0.011173    │
│              ┆ lek         ┆             ┆             ┆             ┆             ┆             │
│ Naira        ┆ US dollar   ┆ 176         ┆ 1           ┆ false       ┆ 0.000019    ┆ 0.005682    │
│ Naira        ┆ Indian      ┆ 175         ┆ 0           ┆ false       ┆ 0.000018    ┆ 0.0         │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ US dollar    ┆ Mexican     ┆ 174         ┆ 0           ┆ false       ┆ 0.000018    ┆ 0.0         │
│              ┆ Peso        ┆             ┆             ┆             ┆             ┆             │
│ Turkish lira ┆ Yen         ┆ 173         ┆ 2           ┆ false       ┆ 0.000018    ┆ 0.011561    │
│ Swiss franc  ┆ US dollar   ┆ 172         ┆ 1           ┆ false       ┆ 0.000018    ┆ 0.005814    │
│ Albanian lek ┆ Albanian    ┆ 170         ┆ 2           ┆ true        ┆ 0.000018    ┆ 0.011765    │
│              ┆ lek         ┆             ┆             ┆             ┆             ┆             │
│ Indian rupee ┆ Dirham      ┆ 169         ┆ 1           ┆ false       ┆ 0.000018    ┆ 0.005917    │
│ Naira        ┆ Turkish     ┆ 169         ┆ 2           ┆ false       ┆ 0.000018    ┆ 0.011834    │
│              ┆ lira        ┆             ┆             ┆             ┆             ┆             │
│ Swiss franc  ┆ Swiss franc ┆ 168         ┆ 3           ┆ true        ┆ 0.000018    ┆ 0.017857    │
│ Moroccan     ┆ Turkish     ┆ 167         ┆ 0           ┆ false       ┆ 0.000018    ┆ 0.0         │
│ dirham       ┆ lira        ┆             ┆             ┆             ┆             ┆             │
│ Pakistani    ┆ Mexican     ┆ 167         ┆ 0           ┆ false       ┆ 0.000018    ┆ 0.0         │
│ rupee        ┆ Peso        ┆             ┆             ┆             ┆             ┆             │
│ Turkish lira ┆ Albanian    ┆ 165         ┆ 4           ┆ false       ┆ 0.000017    ┆ 0.024242    │
│              ┆ lek         ┆             ┆             ┆             ┆             ┆             │
│ Turkish lira ┆ Naira       ┆ 160         ┆ 3           ┆ false       ┆ 0.000017    ┆ 0.01875     │
│ Moroccan     ┆ Albanian    ┆ 160         ┆ 2           ┆ false       ┆ 0.000017    ┆ 0.0125      │
│ dirham       ┆ lek         ┆             ┆             ┆             ┆             ┆             │
│ Yen          ┆ Turkish     ┆ 159         ┆ 0           ┆ false       ┆ 0.000017    ┆ 0.0         │
│              ┆ lira        ┆             ┆             ┆             ┆             ┆             │
│ Indian rupee ┆ Albanian    ┆ 158         ┆ 1           ┆ false       ┆ 0.000017    ┆ 0.006329    │
│              ┆ lek         ┆             ┆             ┆             ┆             ┆             │
│ Mexican Peso ┆ Yen         ┆ 158         ┆ 2           ┆ false       ┆ 0.000017    ┆ 0.012658    │
│ Mexican Peso ┆ Naira       ┆ 158         ┆ 4           ┆ false       ┆ 0.000017    ┆ 0.025316    │
│ US dollar    ┆ Swiss franc ┆ 158         ┆ 1           ┆ false       ┆ 0.000017    ┆ 0.006329    │
│ Moroccan     ┆ Swiss franc ┆ 157         ┆ 3           ┆ false       ┆ 0.000017    ┆ 0.019108    │
│ dirham       ┆             ┆             ┆             ┆             ┆             ┆             │
│ Dirham       ┆ Pakistani   ┆ 157         ┆ 3           ┆ false       ┆ 0.000017    ┆ 0.019108    │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ Indian rupee ┆ Swiss franc ┆ 157         ┆ 0           ┆ false       ┆ 0.000017    ┆ 0.0         │
│ Dirham       ┆ Naira       ┆ 157         ┆ 3           ┆ false       ┆ 0.000017    ┆ 0.019108    │
│ Swiss franc  ┆ Turkish     ┆ 157         ┆ 2           ┆ false       ┆ 0.000017    ┆ 0.012739    │
│              ┆ lira        ┆             ┆             ┆             ┆             ┆             │
│ Swiss franc  ┆ Indian      ┆ 156         ┆ 1           ┆ false       ┆ 0.000016    ┆ 0.00641     │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ Pakistani    ┆ Indian      ┆ 154         ┆ 0           ┆ false       ┆ 0.000016    ┆ 0.0         │
│ rupee        ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ Moroccan     ┆ Mexican     ┆ 153         ┆ 0           ┆ false       ┆ 0.000016    ┆ 0.0         │
│ dirham       ┆ Peso        ┆             ┆             ┆             ┆             ┆             │
│ Yen          ┆ Naira       ┆ 153         ┆ 0           ┆ false       ┆ 0.000016    ┆ 0.0         │
│ Indian rupee ┆ Mexican     ┆ 153         ┆ 2           ┆ false       ┆ 0.000016    ┆ 0.013072    │
│              ┆ Peso        ┆             ┆             ┆             ┆             ┆             │
│ Turkish lira ┆ Indian      ┆ 151         ┆ 1           ┆ false       ┆ 0.000016    ┆ 0.006623    │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ US dollar    ┆ Dirham      ┆ 151         ┆ 3           ┆ false       ┆ 0.000016    ┆ 0.019868    │
│ Indian rupee ┆ US dollar   ┆ 151         ┆ 2           ┆ false       ┆ 0.000016    ┆ 0.013245    │
│ Albanian lek ┆ Swiss franc ┆ 150         ┆ 0           ┆ false       ┆ 0.000016    ┆ 0.0         │
│ Swiss franc  ┆ Yen         ┆ 149         ┆ 4           ┆ false       ┆ 0.000016    ┆ 0.026846    │
│ Swiss franc  ┆ Pakistani   ┆ 148         ┆ 3           ┆ false       ┆ 0.000016    ┆ 0.02027     │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ Pakistani    ┆ Albanian    ┆ 148         ┆ 2           ┆ false       ┆ 0.000016    ┆ 0.013514    │
│ rupee        ┆ lek         ┆             ┆             ┆             ┆             ┆             │
│ Mexican Peso ┆ Swiss franc ┆ 147         ┆ 1           ┆ false       ┆ 0.000015    ┆ 0.006803    │
│ Yen          ┆ Moroccan    ┆ 147         ┆ 2           ┆ false       ┆ 0.000015    ┆ 0.013605    │
│              ┆ dirham      ┆             ┆             ┆             ┆             ┆             │
│ Naira        ┆ Swiss franc ┆ 146         ┆ 1           ┆ false       ┆ 0.000015    ┆ 0.006849    │
│ Mexican Peso ┆ Pakistani   ┆ 146         ┆ 0           ┆ false       ┆ 0.000015    ┆ 0.0         │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ US dollar    ┆ Pakistani   ┆ 144         ┆ 2           ┆ false       ┆ 0.000015    ┆ 0.013889    │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ Indian rupee ┆ Yen         ┆ 144         ┆ 1           ┆ false       ┆ 0.000015    ┆ 0.006944    │
│ Moroccan     ┆ Dirham      ┆ 143         ┆ 1           ┆ false       ┆ 0.000015    ┆ 0.006993    │
│ dirham       ┆             ┆             ┆             ┆             ┆             ┆             │
│ Moroccan     ┆ Yen         ┆ 143         ┆ 0           ┆ false       ┆ 0.000015    ┆ 0.0         │
│ dirham       ┆             ┆             ┆             ┆             ┆             ┆             │
│ Indian rupee ┆ Pakistani   ┆ 139         ┆ 1           ┆ false       ┆ 0.000015    ┆ 0.007194    │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ US dollar    ┆ Yen         ┆ 139         ┆ 2           ┆ false       ┆ 0.000015    ┆ 0.014388    │
│ Swiss franc  ┆ Moroccan    ┆ 139         ┆ 3           ┆ false       ┆ 0.000015    ┆ 0.021583    │
│              ┆ dirham      ┆             ┆             ┆             ┆             ┆             │
│ Moroccan     ┆ Indian      ┆ 137         ┆ 2           ┆ false       ┆ 0.000014    ┆ 0.014599    │
│ dirham       ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ Albanian lek ┆ Moroccan    ┆ 137         ┆ 1           ┆ false       ┆ 0.000014    ┆ 0.007299    │
│              ┆ dirham      ┆             ┆             ┆             ┆             ┆             │
│ Dirham       ┆ Swiss franc ┆ 136         ┆ 1           ┆ false       ┆ 0.000014    ┆ 0.007353    │
│ Turkish lira ┆ Moroccan    ┆ 134         ┆ 0           ┆ false       ┆ 0.000014    ┆ 0.0         │
│              ┆ dirham      ┆             ┆             ┆             ┆             ┆             │
│ Dirham       ┆ Yen         ┆ 134         ┆ 0           ┆ false       ┆ 0.000014    ┆ 0.0         │
│ Dirham       ┆ Moroccan    ┆ 133         ┆ 2           ┆ false       ┆ 0.000014    ┆ 0.015038    │
│              ┆ dirham      ┆             ┆             ┆             ┆             ┆             │
│ Swiss franc  ┆ Dirham      ┆ 132         ┆ 0           ┆ false       ┆ 0.000014    ┆ 0.0         │
│ Dirham       ┆ Turkish     ┆ 132         ┆ 4           ┆ false       ┆ 0.000014    ┆ 0.030303    │
│              ┆ lira        ┆             ┆             ┆             ┆             ┆             │
│ Moroccan     ┆ Naira       ┆ 132         ┆ 0           ┆ false       ┆ 0.000014    ┆ 0.0         │
│ dirham       ┆             ┆             ┆             ┆             ┆             ┆             │
│ Naira        ┆ Pakistani   ┆ 132         ┆ 0           ┆ false       ┆ 0.000014    ┆ 0.0         │
│              ┆ rupee       ┆             ┆             ┆             ┆             ┆             │
│ Albanian lek ┆ Turkish     ┆ 132         ┆ 3           ┆ false       ┆ 0.000014    ┆ 0.022727    │
│              ┆ lira        ┆             ┆             ┆             ┆             ┆             │

shape: (26, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ payment_c ┆ is_launde ┆ transacti ┆ minimum_a ┆ … ┆ amount_q9 ┆ amount_q9 ┆ maximum_a ┆ mean_amo │
│ urrency   ┆ ring      ┆ on_count  ┆ mount     ┆   ┆ 5         ┆ 9         ┆ mount     ┆ unt      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ i8        ┆ u64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Albanian  ┆ 0         ┆ 24714     ┆ 18.82     ┆ … ┆ 23832.511 ┆ 48922.280 ┆ 935820.72 ┆ 9615.598 │
│ lek       ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆           ┆ 072      │
│ Albanian  ┆ 1         ┆ 64        ┆ 2800.75   ┆ … ┆ 34732.939 ┆ 52116.954 ┆ 75683.499 ┆ 10711.80 │
│ lek       ┆           ┆           ┆           ┆   ┆ 205       ┆ 846       ┆ 559       ┆ 3623     │
│ Dirham    ┆ 0         ┆ 27174     ┆ 17.17     ┆ … ┆ 23679.271 ┆ 49462.573 ┆ 956193.0  ┆ 9907.217 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 9         ┆           ┆ 582      │
│ Dirham    ┆ 1         ┆ 89        ┆ 2259.18   ┆ … ┆ 37250.534 ┆ 58730.145 ┆ 62867.858 ┆ 10902.37 │
│           ┆           ┆           ┆           ┆   ┆ 444       ┆ 957       ┆ 744       ┆ 1375     │
│ Euro      ┆ 0         ┆ 116904    ┆ 9.15      ┆ … ┆ 25429.531 ┆ 53604.742 ┆ 995675.88 ┆ 10523.26 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 3         ┆           ┆ 9269     │
│ Euro      ┆ 1         ┆ 260       ┆ 1250.41   ┆ … ┆ 66535.648 ┆ 154557.23 ┆ 294167.63 ┆ 16758.71 │
│           ┆           ┆           ┆           ┆   ┆ 256       ┆ 9406      ┆           ┆ 4386     │
│ Indian    ┆ 0         ┆ 24589     ┆ 13.41     ┆ … ┆ 24032.4   ┆ 55993.225 ┆ 985678.03 ┆ 10217.44 │
│ rupee     ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆ 6434     │
│ Indian    ┆ 1         ┆ 68        ┆ 2618.8    ┆ … ┆ 23943.533 ┆ 66606.854 ┆ 67635.42  ┆ 9736.177 │
│ rupee     ┆           ┆           ┆           ┆   ┆ 39        ┆ 691       ┆           ┆ 476      │
│ Mexican   ┆ 0         ┆ 24784     ┆ 5.9       ┆ … ┆ 25546.058 ┆ 50473.195 ┆ 992045.52 ┆ 10212.46 │
│ Peso      ┆           ┆           ┆           ┆   ┆           ┆ 3         ┆           ┆ 6525     │
│ Mexican   ┆ 1         ┆ 68        ┆ 2302.4    ┆ … ┆ 41611.135 ┆ 1.3808e6  ┆ 1.9288e6  ┆ 54143.33 │
│ Peso      ┆           ┆           ┆           ┆   ┆ 35        ┆           ┆           ┆ 0654     │
│ Moroccan  ┆ 0         ┆ 25305     ┆ 18.17     ┆ … ┆ 24168.968 ┆ 48566.942 ┆ 883295.9  ┆ 10072.19 │
│ dirham    ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ 8528     │
│ Moroccan  ┆ 1         ┆ 90        ┆ 903.59    ┆ … ┆ 266510.88 ┆ 2.9938e6  ┆ 5.8816e6  ┆ 129704.5 │
│ dirham    ┆           ┆           ┆           ┆   ┆ 85        ┆           ┆           ┆ 76774    │
│ Naira     ┆ 0         ┆ 27081     ┆ 13.91     ┆ … ┆ 23989.51  ┆ 58323.062 ┆ 980326.83 ┆ 10438.99 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2301     │
│ Naira     ┆ 1         ┆ 62        ┆ 2291.54   ┆ … ┆ 14016.039 ┆ 21540.310 ┆ 30192.52  ┆ 6858.627 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆ 882      │
│ Pakistani ┆ 0         ┆ 27134     ┆ 10.14     ┆ … ┆ 24053.939 ┆ 46927.716 ┆ 893360.76 ┆ 10131.44 │
│ rupee     ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ 1829     │
│ Pakistani ┆ 1         ┆ 62        ┆ 1919.9    ┆ … ┆ 29467.555 ┆ 46467.659 ┆ 50791.966 ┆ 9650.833 │
│ rupee     ┆           ┆           ┆           ┆   ┆ 532       ┆ 381       ┆ 303       ┆ 882      │
│ Swiss     ┆ 0         ┆ 27410     ┆ 14.01     ┆ … ┆ 24666.959 ┆ 52354.132 ┆ 980925.83 ┆ 10391.66 │
│ franc     ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆           ┆ 1331     │
│ Swiss     ┆ 1         ┆ 82        ┆ 2172.7567 ┆ … ┆ 42819.645 ┆ 4.2378e6  ┆ 6.8122e6  ┆ 137133.2 │
│ franc     ┆           ┆           ┆ 35        ┆   ┆ 437       ┆           ┆           ┆ 45456    │
│ Turkish   ┆ 0         ┆ 27923     ┆ 15.25     ┆ … ┆ 24141.593 ┆ 48043.613 ┆ 990051.52 ┆ 9786.112 │
│ lira      ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ 111      │
│ Turkish   ┆ 1         ┆ 73        ┆ 2652.74   ┆ … ┆ 38375.819 ┆ 73336.161 ┆ 104896.34 ┆ 11315.22 │
│ lira      ┆           ┆           ┆           ┆   ┆ 833       ┆ 396       ┆ 1152      ┆ 7247     │
│ UK pounds ┆ 0         ┆ 9090463   ┆ 3.73      ┆ … ┆ 21926.029 ┆ 44566.666 ┆ 999962.19 ┆ 8664.101 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ 864      │
│ UK pounds ┆ 1         ┆ 8830      ┆ 15.82     ┆ … ┆ 38619.462 ┆ 421175.13 ┆ 1.2618e7  ┆ 41243.59 │
│           ┆           ┆           ┆           ┆   ┆ 183       ┆ 85        ┆           ┆ 3975     │
│ US dollar ┆ 0         ┆ 26001     ┆ 20.23     ┆ … ┆ 23419.41  ┆ 48302.31  ┆ 881277.95 ┆ 10162.20 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8416     │
│ US dollar ┆ 1         ┆ 60        ┆ 1098.71   ┆ … ┆ 43619.515 ┆ 47276.380 ┆ 47342.12  ┆ 11610.22 │
│           ┆           ┆           ┆           ┆   ┆ 05        ┆ 652       ┆           ┆ 5264     │
│ Yen       ┆ 0         ┆ 25497     ┆ 10.47     ┆ … ┆ 23622.402 ┆ 52550.315 ┆ 828398.2  ┆ 9925.666 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆ 218      │
│ Yen       ┆ 1         ┆ 65        ┆ 2608.19   ┆ … ┆ 30963.072 ┆ 56184.575 ┆ 66876.853 ┆ 11070.95 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 131       ┆ 706       ┆ 3946     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
### laundering typology summary
# laundering typology
laundering_typology_summary = transaction_eda.get_typology_summary(
    label = 1
)

# legitimate typology
normal_typology_summary = transaction_eda.get_typology_summary(
    label = 0
)

with pl.Config(tbl_rows = -1):
    display(laundering_typology_summary)
    display(normal_typology_summary)

shape: (17, 4)
┌───────────────┬──────────────────────┬───────────────────┬────────────────────┐
│ is_laundering ┆ laundering_type      ┆ transaction_count ┆ share_within_label │
│ ---           ┆ ---                  ┆ ---               ┆ ---                │
│ i8            ┆ str                  ┆ u64               ┆ f64                │
╞═══════════════╪══════════════════════╪═══════════════════╪════════════════════╡
│ 1             ┆ Structuring          ┆ 1870              ┆ 0.189405           │
│ 1             ┆ Stacked Bipartite    ┆ 506               ┆ 0.051251           │
│ 1             ┆ Smurfing             ┆ 932               ┆ 0.094399           │
│ 1             ┆ Single_large         ┆ 250               ┆ 0.025322           │
│ 1             ┆ Scatter-Gather       ┆ 338               ┆ 0.034235           │
│ 1             ┆ Over-Invoicing       ┆ 54                ┆ 0.005469           │
│ 1             ┆ Layered_Fan_Out      ┆ 529               ┆ 0.05358            │
│ 1             ┆ Layered_Fan_In       ┆ 656               ┆ 0.066444           │
│ 1             ┆ Gather-Scatter       ┆ 354               ┆ 0.035855           │
│ 1             ┆ Fan_Out              ┆ 237               ┆ 0.024005           │
│ 1             ┆ Fan_In               ┆ 364               ┆ 0.036868           │
│ 1             ┆ Deposit-Send         ┆ 945               ┆ 0.095716           │
│ 1             ┆ Cycle                ┆ 382               ┆ 0.038691           │
│ 1             ┆ Cash_Withdrawal      ┆ 1334              ┆ 0.135116           │
│ 1             ┆ Bipartite            ┆ 383               ┆ 0.038793           │
│ 1             ┆ Behavioural_Change_2 ┆ 345               ┆ 0.034944           │
│ 1             ┆ Behavioural_Change_1 ┆ 394               ┆ 0.039907           │
└───────────────┴──────────────────────┴───────────────────┴────────────────────┘

shape: (11, 4)
┌───────────────┬────────────────────────┬───────────────────┬────────────────────┐
│ is_laundering ┆ laundering_type        ┆ transaction_count ┆ share_within_label │
│ ---           ┆ ---                    ┆ ---               ┆ ---                │
│ i8            ┆ str                    ┆ u64               ┆ f64                │
╞═══════════════╪════════════════════════╪═══════════════════╪════════════════════╡
│ 0             ┆ Normal_single_large    ┆ 20641             ┆ 0.002174           │
│ 0             ┆ Normal_Small_Fan_Out   ┆ 3477717           ┆ 0.366269           │
│ 0             ┆ Normal_Plus_Mutual     ┆ 155041            ┆ 0.016329           │
│ 0             ┆ Normal_Periodical      ┆ 210526            ┆ 0.022172           │
│ 0             ┆ Normal_Mutual          ┆ 125335            ┆ 0.0132             │
│ 0             ┆ Normal_Group           ┆ 528351            ┆ 0.055645           │
│ 0             ┆ Normal_Foward          ┆ 42031             ┆ 0.004427           │
│ 0             ┆ Normal_Fan_Out         ┆ 2302220           ┆ 0.242467           │
│ 0             ┆ Normal_Fan_In          ┆ 2104285           ┆ 0.221621           │
│ 0             ┆ Normal_Cash_Withdrawal ┆ 305031            ┆ 0.032126           │
│ 0             ┆ Normal_Cash_Deposits   ┆ 223801            ┆ 0.02357            │
└───────────────┴────────────────────────┴───────────────────┴────────────────────┘

In [8]:
### account identity overview
# account overview
account_overview = transaction_eda.get_account_overview()

display(account_overview)

shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ unique_accou ┆ suspicious_ ┆ sender_and_ ┆ sender_only ┆ receiver_on ┆ multi_locat ┆ suspicious_ │
│ nt_count     ┆ account_cou ┆ receiver_co ┆ _count      ┆ ly_count    ┆ ion_account ┆ account_rat │
│ ---          ┆ nt          ┆ unt         ┆ ---         ┆ ---         ┆ _count      ┆ e           │
│ u64          ┆ ---         ┆ ---         ┆ u64         ┆ u64         ┆ ---         ┆ ---         │
│              ┆ u64         ┆ u64         ┆             ┆             ┆ u64         ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 855460       ┆ 7902        ┆ 89521       ┆ 203194      ┆ 562745      ┆ 6507        ┆ 0.009237    │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [9]:
### multi location account summary
# multi bank location account count
multi_location_account_count = int(
    account_overview['multi_location_account_count'][0]
)

# check if multi location account count is non-negative
if multi_location_account_count > 0:
    multi_location_accounts = transaction_eda.get_multi_location_accounts(
        limit = 20
    )

    display(multi_location_accounts)
else:
    print(
        'No accounts are associated with multiple bank locations.'
    )

# total multi_location accounts
if multi_location_account_count > 0:
    max_int32 = np.iinfo(np.int32).max

    max_multi_location_accounts = transaction_eda.get_multi_location_accounts(
        limit = max_int32
    )

    print(
        f'Total multi-location accounts: {max_multi_location_accounts.shape[0]}'
    )

shape: (20, 4)
┌────────────┬─────────────────────┬─────────────────────────────────┬─────────────────────┐
│ account    ┆ bank_location_count ┆ bank_locations                  ┆ account_event_count │
│ ---        ┆ ---                 ┆ ---                             ┆ ---                 │
│ str        ┆ u32                 ┆ list[str]                       ┆ u64                 │
╞════════════╪═════════════════════╪═════════════════════════════════╪═════════════════════╡
│ 7823743088 ┆ 5                   ┆ ["Austria", "India", … "USA"]   ┆ 810                 │
│ 6636772831 ┆ 5                   ┆ ["Nigeria", "Spain", … "UK"]    ┆ 777                 │
│ 6517474457 ┆ 5                   ┆ ["Austria", "India", … "UK"]    ┆ 723                 │
│ 5708009014 ┆ 5                   ┆ ["Albania", "Turkey", … "USA"]  ┆ 710                 │
│ 1168600456 ┆ 5                   ┆ ["India", "Netherlands", … "UK… ┆ 585                 │
│ …          ┆ …                   ┆ …                               ┆ …                   │
│ 4035147493 ┆ 4                   ┆ ["Austria", "Italy", … "UK"]    ┆ 739                 │
│ 453377489  ┆ 4                   ┆ ["Japan", "Morocco", … "UK"]    ┆ 733                 │
│ 2384413935 ┆ 4                   ┆ ["Morocco", "Netherlands", … "… ┆ 729                 │
│ 3501288993 ┆ 4                   ┆ ["Germany", "Turkey", … "USA"]  ┆ 718                 │
│ 5715771307 ┆ 4                   ┆ ["India", "Mexico", … "UK"]     ┆ 702                 │
└────────────┴─────────────────────┴─────────────────────────────────┴─────────────────────┘

Total multi-location accounts: 6507

In [10]:
### graph-size and duplicate summaries
# directed pair summary
directed_pair_summary = transaction_eda.get_directed_pair_summary()

# duplicate summary
duplicate_summary = transaction_eda.get_duplicate_summary()

display(directed_pair_summary)
display(duplicate_summary)

shape: (1, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ directed_pair_cou ┆ repeated_directed ┆ maximum_transacti ┆ mean_transactions ┆ repeated_directe │
│ nt                ┆ _pair_count       ┆ ons_per_pair      ┆ _per_pair         ┆ d_pair_rate      │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│ u64               ┆ u64               ┆ u64               ┆ f64               ┆ f64              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ 887497            ┆ 781631            ┆ 84                ┆ 10.709729         ┆ 0.880714         │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

shape: (1, 4)
┌───────────────────────┬─────────────────────────┬─────────────────────────┬──────────────────────┐
│ duplicate_group_count ┆ rows_in_duplicate_group ┆ duplicate_excess_row_co ┆ maximum_multiplicity │
│ ---                   ┆ s                       ┆ unt                     ┆ ---                  │
│ u64                   ┆ ---                     ┆ ---                     ┆ u64                  │
│                       ┆ u64                     ┆ u64                     ┆                      │
╞═══════════════════════╪═════════════════════════╪═════════════════════════╪══════════════════════╡
│ 0                     ┆ 0                       ┆ 0                       ┆ 0                    │
└───────────────────────┴─────────────────────────┴─────────────────────────┴──────────────────────┘

**Design Decisions**

Translating transaction-level EDA outputs into graph-design decisions:

- 887k directed account pairs out of 9.5m total transactions
    - Aggregate transactions by sender-receiver pair
- 88.07% of directed pairs repeat
    - Use transaction count as the first edge weight
- No exact duplicates
    - No deduplication step is required
- 13 currencies and strongly skewed amounts
    - Should not be summing raw amounts across currencies
- 6507 multi-location accounts
    - Keep one node per account
- 0.1039% laundering transactions
    - Use ranking metrics
- 17 laundering typologies
    - Report results separately by typology
- Final date contains only 8.4k transactions
    - Exclude the incomplete date from test evaluation